version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - VALID_CODE=${VALID_CODE}
      - WELCOME_VIDEO_NOTES=${WELCOME_VIDEO_NOTES}
    restart: always